---
# This is a sample database file for the Sequel ORM
:development: &defaults
  :adapter: mysql
  :database: chunky_bacon
  :username: root
  :host: localhost

:test:
  <<: *defaults

:production:
  <<: *defaults
